### ISSUE TITLE
error: ‘readdir_r’ is deprecated

### ISSUE THREAD

**Issue by gps3dx** [anestisb/dexRepair#1]
Hello,
when I tried to cross-compile on lubuntu 16.04 into arm64 I got 'error: ‘readdir_r’ is deprecated'.

shell log is:
`lubuntu@lubuntu:~/dexRepair$ ./make.sh 
make: Entering directory '/home/lubuntu/dexRepair/src'
rm -f *.o
rm -f dexRepair
make: Leaving directory '/home/lubuntu/dexRepair/src'
make: Entering directory '/home/lubuntu/dexRepair/src'
cc -c -std=c11 -D_GNU_SOURCE -Wall -Wextra -Werror -c dexRepair.c -o dexRepair.o
cc -c -std=c11 -D_GNU_SOURCE -Wall -Wextra -Werror -c log.c -o log.o
cc -c -std=c11 -D_GNU_SOURCE -Wall -Wextra -Werror -c utils.c -o utils.o
utils.c: In function ‘utils_readdir’:
utils.c:45:9: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
         if (readdir_r(dir, &de, &res) > 0) {
         ^~
In file included from utils.c:26:0:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
cc1: all warnings being treated as errors
Makefile:36: recipe for target 'utils.o' failed
make: *** [utils.o] Error 1
make: Leaving directory '/home/lubuntu/dexRepair/src'
[-] gcc build failed`

Can you please update utils.c so that it will be compatible with readdir command instead of readdir_r ?

**Also, it will be REALLY HELPFUL if you could compile dexRepair and publish the bin for arm & arm64**, since source compiling is HARD for me.

**Comment by anestisb** [comment]
Thanks for the bug report. Will have a look at it later today.

Considering the multiple combinations of NDK + target API versions I try to avoid distributing binaries since people keep asking for "another missing" combo. Since this is a very simple tool I might consider distributing a version with a relatively recent NDK + target API.

**Comment by anestisb** [comment]
Pushed a patch. Let me know if that worked for you.

**Comment by gps3dx** [comment]
@anestisb - it works like butter now ! much oblige :-) :+1: 

P.S - although I manage to compile it, it does not run on my arm64 phone, complaining "not executable: 32 bit-ELF".
is this the right place to ask for your help about it, since the bug is "solved" ?
is there a project specific forum here on github or direct email that you might be willing to help me ?

pre-compelation I ran `export GOARCH=arm64 CC=aarch64-linux-gnu-gcc CGO_ENABLED=1` - since this is AFAIK the command to config cross-compilation for arm64.
I try to compile on a x32 lubuntu 16.04.
am I wrong ?

much obliged :-)

UPDATE:
OK I using the following command I fgound out that I still compile for i386, not arm or arm64 at all.
`objdump -x dexRepair | grep arch | cut --delimiter=" " -f 2 | cut --delimiter="," -f 1`
@anestisb - how should I instruct "make.sh" to compile for arm/arm64 ?

**Comment by anestisb** [comment]
I've already included cross-compilation for Android targets (ARM/ARM64). Install Android NDK and run `$ ./make.sh cross-android`. Under the `bin` folder you should find the `dexRepair-arm64-v8a` executable which matches the aarch64 (ARM64) CPU.

**Comment by gps3dx** [comment]
yes you have -> I managed to cross-compile it for android ! :-)
the only thing I was missing is android ndk's PATH config:
`export PATH=$PATH:/<path to ndk root folder folder>`
then indeed I ran the command you wrote above -> and I managed to compile dexRepair for arm,arm64 etc.. !

this is wonderful !
THANK YOU FOR YOUR FAST REPLY AND PATIENCE :-) you're the best ! :+1: :+1: :+1:

**Comment by anestisb** [comment]
Glad it worked.

**Comment by gps3dx** [comment]
@anestisb - since github don't have requests/PM area... I post here my request:
dexRepair can fix dex file checksum, but not its [SHA-1 signature](http://www.phonesdevelopers.info/1739395/).
can you please add SHA-1 signature repair as well to dexRepair ?
IMHO, it would be advisable to separate it as a different switch then the already existing checksum repair, since SHA-1 repair should come before adler32 checksum.

I hope you can add such feature to the already great dexRepair :-)

**Comment by anestisb** [comment]
You can open a new issue and label it as feature request. As soon as you do it I'll comment you on that so that we can keep the existing issues clean in terms of context.
